modLoader="javafml"
loaderVersion="[46,)"
license="MIT"
issueTrackerURL="https://github.com/dhyces/charm-of-return/issues"
[[mods]]
modId="charmofreturn"
version="${file.jarVersion}"
displayName="Charm of Return"
displayURL="https://www.curseforge.com/minecraft/mc-mods/charm-of-return"
logoFile="icon.png"
authors="Dhyces"
description='''
Magic mirror, but it's a charm. Return to spawn point!
'''

[[dependencies.charmofreturn]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.charmofreturn]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.20.2)"
    ordering="NONE"
    side="BOTH"
